#!/bin/sh -e

[ -r ~/.parrot-smoker.conf ] && . ~/.parrot-smoker.conf

# set defaults
: ${PARROT_REPOSITORY:=~/.smokers/parrot}
: ${TEST_JOBS:=6}
: ${MAKE_JOBS:=6}
: ${HARNESS_VERBOSE:=-2}

export SMOLDER_SUBMITTER TEST_JOBS HARNESS_VERBOSE

MAKE_OPTS="-j${MAKE_JOBS}"

# create a new clone if it doesn't exist already
if ! [ -d "$PARROT_REPOSITORY" ]
then
  git clone git://github.com/parrot/parrot.git $PARROT_REPOSITORY
fi

# the branch to test
BRANCH='origin/master'

cd $PARROT_REPOSITORY
old_head=`git rev-parse $BRANCH`
git pull -q
new_head=`git rev-parse $BRANCH`

# nothing to do...
[ -n "$old_head" -a "$old_head" = "$new_head" ] && exit;

# only test if one or more files matching this pattern have been modified
FILE_PATTERN='\.(pm|[chtly]|in|ops|pir|pmc|tg)$'

if git diff --name-only "$old_head..$new_head" | grep -qE $FILE_PATTERN
then
    PARROT_SMOKE_DIR=`mktemp -d`
    [ -n "$PARROT_SMOKE_DIR" ] || exit;

    git archive --format=tar $new_head | (
      cd $PARROT_SMOKE_DIR

      tar xf -

      perl Configure.pl --silent
      make --silent $MAKE_OPTS
      make --silent smoke

      rm -rf $PARROT_SMOKE_DIR
  )
fi

exit

: <<"POD"

=head1 parrot

Smoker script for Parrot.

=head1 Configuration

The defaults should be more or less sane.  If you want to override any of them
create a file called C<.parrot-config.conf> in the root of your home directory
and put your custom settings there.  It should just be a normal shell script.
eg.

  PARROT_REPOSITORY=~/projects/parrot
  TEST_JOBS=2

=over 4

=item C<PARROT_REPOSITORY>

The directory with a master clone of Parrot.

=item C<TEST_JOBS>

The number of tests to run in parallel.  Default is 6.

=item C<MAKE_JOBS>

The number of parallel make jobs to use.  Default is 6.

=item C<HARNESS_VERBOSE>

The test harness verbosity.  Default value is -2 (only displays the
final summary).  Set this to -3 for a completely silent test harness (bar any
errors), or to 0 for the normal output.

=item C<SMOLDER_SUBMITTER>

The email address the smoke report should be submitted as.  No default, since
the Parrot test harness can usually make a good guess at a sensible value.

=back

=cut
POD

