=head1 Smoke testers

Scripts to automatically smoke-test various projects.  Currently both
L<Parrot|http://www.parrot.org/> and L<Rakudo Perl 6|http://rakudo.org/> are
supported.

Use C<perldoc $script_name> to view documentation on individual scripts.

Example cron entries:

  31 */4 * * * exec dash /path/to/smoke/testers/parrot-smoker
  44 03  * * * exec dash /path/to/smoke/testers/rakudo-smoker

(These will run the Parrot test suite every 4h, and the Rakudo test suite once
a night.)

